---
label: Producto
hide_body: false
fields:
- name: date
  type: datetime
  label: Fecha
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  hidden: true
  default: now
- name: title
  type: text
  config:
    required: true
  label: Título de la publicacion
  description: Indica el título de la publicación. <strong>Evita colocar el precio
    en el título!</strong>
- name: unit_price
  type: text
  config:
    required: true
  label: Precio del producto
  description: Precio del producto sin <strong>"$"</strong> o <strong>"USD"</strong>.
    p.ej. 160.00
- name: description
  type: text
  config:
    required: true
  label: Descripción
  description: Corta y breve descripción del producto
- name: category
  type: select
  default: Piedras preciosas
  config:
    required: true
    options:
    - Celulares
    - Accesorios
    - Reparaciones
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Categoría
  description: Indica la categoría del producto
- name: cover_img
  type: file
  config:
    maxSize: 64
  label: Foto de portada
  description: Foto de portada del producto
- name: images
  type: image_gallery
  config: {}
  label: Fotos del producto
  description: Evita subir fotos con la extensión en mayuscula. p.ej. <strong>.JPG,
    .PNG</strong>, etc
- name: available
  type: boolean
  label: Producto disponible
  description: Indica si el producto esta disponible
  default: true
pages:
- products/celular-huawei-y5-2019-amn-lx3.md
- products/huawei-p40-lite-128gb-6gb-ram.md
- products/huawei-y9-prime-stk-lx3.md
- products/lg-k40-32-gb-de-memoria-interna-y-2-ram.md
- products/reparacion-de-telefonos.md
- products/samsung-a01-sm-a015f-ds-16gb-2gb-ram.md
- products/samsung-a10s-32-gb-de-memria-interna-y-2-gb-ram.md
- products/samsung-a31-sm-a315f-ds-128gb-4gb-ram.md
- products/samsung-a71-sm-a715f-ds-128gb-6gb-ram.md
- products/xiaomi-note-8-128gb-6gb-ram.md
- products/xiaomi-note-8-pro-128gb-6gb-ram.md
- products/xiaomi-note-9s-128gb.md
- products/y7p-no-google-play-services.md
